#!/usr/bin/python

import sys
import os
import numpy as np
import cv2
from pylepton import Lepton

ROOT_PATH = os.getcwd()
N_SAMPLES = 10

def capture(flip_v = False, device = "/dev/spidev0.0"):
  with Lepton(device) as l:
    a,_ = l.capture()
  if flip_v:
    cv2.flip(a,0,a)
  cv2.normalize(a, a, 0, 65535, cv2.NORM_MINMAX)
  np.right_shift(a, 8, a)
  return np.uint8(a)

if __name__ == '__main__':
  
  counter = 0

  while(counter<N_SAMPLES)

    image = capture(flip_v = options.flip_v, device = options.device)
    cv2.imwrite(os.path.join(ROOT_PATH,"Evaluate/{0}.ppm".format(counter)),image)
    counter = counter+1
