# Generated by Django 2.0.7 on 2018-07-13 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedidaEletromagnetica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('dado', models.FilePathField()),
                ('fMinima', models.FloatField()),
                ('fMaxima', models.FloatField()),
                ('RBW', models.FloatField()),
                ('PA', models.BooleanField(default=False)),
                ('fonteChaveada', models.BooleanField(default=False)),
                ('correnteFonte', models.PositiveSmallIntegerField(default=0)),
                ('comentarios', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MedidaTermica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('dado', models.FilePathField()),
                ('correnteFonte', models.PositiveSmallIntegerField(default=0)),
                ('comentarios', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('medidor', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fraudado', models.BooleanField(default=False)),
                ('foto', models.FilePathField()),
            ],
        ),
        migrations.AddField(
            model_name='medidatermica',
            name='medidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analise.Medidor'),
        ),
        migrations.AddField(
            model_name='medidaeletromagnetica',
            name='medidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analise.Medidor'),
        ),
    ]
