# Generated by Django 2.0.7 on 2018-07-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidaeletromagnetica',
            name='comentarios',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='medidaeletromagnetica',
            name='dado',
            field=models.FilePathField(match='*.asc', path='/'),
        ),
        migrations.AlterField(
            model_name='medidatermica',
            name='comentarios',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='medidatermica',
            name='dado',
            field=models.FilePathField(match='*.jpg', path='/'),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='foto',
            field=models.FilePathField(match='*.jpg', path='/'),
        ),
    ]
