# Generated by Django 2.0.7 on 2018-07-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0003_auto_20180713_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medidaeletromagnetica',
            name='dado',
        ),
        migrations.RemoveField(
            model_name='medidatermica',
            name='dado',
        ),
        migrations.RemoveField(
            model_name='medidor',
            name='foto',
        ),
    ]
