# Generated by Django 2.0.7 on 2018-07-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0004_auto_20180713_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidaeletromagnetica',
            name='dado',
            field=models.FilePathField(default='/', path='/'),
        ),
        migrations.AddField(
            model_name='medidatermica',
            name='dado',
            field=models.FilePathField(default='/', path='/'),
        ),
        migrations.AddField(
            model_name='medidor',
            name='foto',
            field=models.FilePathField(default='/', path='/'),
        ),
    ]
