# Generated by Django 2.0.7 on 2018-07-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0009_auto_20180713_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidor',
            name='foto',
            field=models.FilePathField(default='/', path='/home/mathias/Downloads', recursive=True),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='medidor',
            field=models.CharField(choices=[('L01-M01', 'MEDIDOR BOM'), ('L01-M02', 'MEDIDOR'), ('L01-M03', 'MEDIDOR RUIM')], max_length=30, primary_key=True, serialize=False),
        ),
    ]
