# Generated by Django 2.0.7 on 2018-07-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0011_auto_20180713_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidor',
            name='medidor',
            field=models.CharField(choices=[('L01-M01 Landys Gyr', 'L01-M01'), ('L01-M02 Landys Gyr', 'L01-M02'), ('L01-M03 Landys Gyr', 'L01-M03'), ('MARCA', 'L01-M04'), ('MARCA', 'L01-M05'), ('MARCA', 'L01-M06'), ('MARCA', 'L01-M07'), ('MARCA', 'L01-M08'), ('MARCA', 'L01-M09'), ('MARCA', 'L01-M10'), ('MARCA', 'L01-M11'), ('MARCA', 'L01-M12'), ('MARCA', 'L01-M13'), ('MARCA', 'L02-M01'), ('MARCA', 'L02-M02'), ('MARCA', 'L02-M03'), ('MARCA', 'L02-M04'), ('MARCA', 'L02-M05'), ('MARCA', 'L02-M06'), ('MARCA', 'L02-M07'), ('MARCA', 'L02-M08'), ('MARCA', 'L02-M09'), ('MARCA', 'L02-M10'), ('MARCA', 'L02-M11'), ('MARCA', 'L02-M12'), ('MARCA', 'L02-M13'), ('MARCA', 'L02-M14'), ('MARCA', 'L02-M15'), ('MARCA', 'L02-M16'), ('MARCA', 'L02-M17'), ('MARCA', 'L02-M18'), ('MARCA', 'L02-M19'), ('MARCA', 'L02-M20')], max_length=30, primary_key=True, serialize=False),
        ),
    ]
