# Generated by Django 2.0.7 on 2018-07-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0013_auto_20180716_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidaeletromagnetica',
            name='dado',
            field=models.FilePathField(default='/', path='/home/mathias/Área de Trabalho/mtd_git/MTD/eletromagnetico/interfaceAnalise/', recursive=True),
        ),
    ]
