# Generated by Django 2.0.7 on 2018-07-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0015_auto_20180716_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidaeletromagnetica',
            name='RBW',
            field=models.FloatField(default=200000.0),
        ),
        migrations.AlterField(
            model_name='medidaeletromagnetica',
            name='dado',
            field=models.FilePathField(default='/', path='/home/mathias/MTD/eletromagnetico/interfaceAnalise', recursive=True),
        ),
        migrations.AlterField(
            model_name='medidaeletromagnetica',
            name='fMaxima',
            field=models.FloatField(default=3000000000.0),
        ),
        migrations.AlterField(
            model_name='medidaeletromagnetica',
            name='fMinima',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='foto',
            field=models.FilePathField(default='/', path='/home/mathias/MTD/eletromagnetico/interfaceAnalise', recursive=True),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='medidor',
            field=models.CharField(choices=[('L01-M01', 'L01-M01'), ('L01-M02', 'L01-M02'), ('L01-M03', 'L01-M03'), ('L01-M04', 'L01-M04'), ('L01-M05', 'L01-M05'), ('L01-M06', 'L01-M06'), ('L01-M07', 'L01-M07'), ('L01-M08', 'L01-M08'), ('L01-M09', 'L01-M09'), ('L01-M10', 'L01-M10'), ('L01-M11', 'L01-M11'), ('L01-M12', 'L01-M12'), ('L01-M13', 'L01-M13'), ('L02-M01', 'L02-M01'), ('L02-M02', 'L02-M02'), ('L02-M03', 'L02-M03'), ('L02-M04', 'L02-M04'), ('L02-M05', 'L02-M05'), ('L02-M06', 'L02-M06'), ('L02-M07', 'L02-M07'), ('L02-M08', 'L02-M08'), ('L02-M09', 'L02-M09'), ('L02-M10', 'L02-M10'), ('L02-M11', 'L02-M11'), ('L02-M12', 'L02-M12'), ('L02-M13', 'L02-M13'), ('L02-M14', 'L02-M14'), ('L02-M15', 'L02-M15'), ('L02-M16', 'L02-M16'), ('L02-M17', 'L02-M17'), ('L02-M18', 'L02-M18'), ('L02-M19', 'L02-M19'), ('L02-M20', 'L02-M20')], max_length=30, primary_key=True, serialize=False),
        ),
    ]
