# Generated by Django 2.0.7 on 2018-07-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0016_auto_20180717_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidaeletromagnetica',
            name='periodo',
            field=models.CharField(choices=[('manha', 'manha'), ('tarde', 'tarde'), ('noite', 'noite')], default='tarde', max_length=30),
        ),
    ]
